[build]
  command = "npm run build"
  publish = "out"

# This single rule directs all non-file requests to index.html,
# allowing the Next.js client-side router to handle the path.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Add security headers back if desired
# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"
#     X-Content-Type-Options = "nosniff"
#     Referrer-Policy = "strict-origin-when-cross-origin"