[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# For Next.js App Router with static export, we need to handle client-side navigation
# The key is to send all product/* requests back to index.html to allow client-side routing to take over
[[redirects]]
  from = "/product/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200

# Handle all other paths for SPA-style client navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200